migrations: @@DAMI_DIRECTORY@@/migrations
current_environment: dev
environments:

    prod:
        adapter:  pgsql
        host:     localhost
        database: dami_prod
        username: postgres
        password:
        port:     5432

    dev:
        adapter:  pgsql
        host:     localhost
        database: dami_dev
        username: aj
        password: aj
        port:     5432

    test:
        adapter:  pgsql
        host:     localhost
        database: dami_test
        username: postgres
        password:
        port:     5432
