parameters:
    service_container.class: Dami\Container;
    api.class: Dami\Migration\Api\ApiMigration;
    template_renderer.class: Dami\Migration\TemplateRenderer
    template_initialization.class: Dami\Migration\TemplateInitialization
    migration_name_parser.class: Dami\Migration\MigrationNameParser

services:
    service_container:
        class: "%service_container.class%"

    migration_name_parser:
        class: "%migration_name_parser.class%"

    template_initialization:
        class: "%template_initialization.class%"
        arguments: [@migration_name_parser]


    template_renderer:
        class: "%template_renderer.class%"
        arguments: [@template_initialization]

    schema_table:
        class: Dami\Migration\SchemaTable
        arguments: [@connection, @schema.manipulation, @schema.info]
